// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofovgpahtnnvhekdodni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mb3ZncGFodG5udmhla2RvZG5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NzkyMzYsImV4cCI6MjA2OTE1NTIzNn0.irWniUsCOMu_2gawTcEWX7CNEFb-AMiDQpW7pRiau3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});